- name: install epel-release
  action : "{{ ansible_pkg_mgr }} name=epel-release state=latest"
- name: install nginx web server
  action : "{{ ansible_pkg_mgr }} name=nginx state=present"
- name: default index.html for web server
  get_url: url=https://www.apache.org dest=/usr/share/nginx/html/ mode=0644
  notify:
    - Restart nginx web server
