---
 - name: Install Docker
   hosts: test
   become: yes
   gather_facts: no
   tasks:

   - name: Docker - apt upgrade, update
     apt:
       upgrade: 'yes'
       update_cache: yes

   - name: Docker - Install Dependency Packages
     apt:
       name: ca-certificates,curl,gnupg,lsb-release
       state: present

   - name: Docker - Delete docker-archive-keyring.gpg
     file:
       path: /usr/share/keyrings/docker-archive-keyring.gpg
       state: absent

   - name: Docker - get Docker-repo gpgkey
     shell: |
       curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
     register: gpg_res
     changed_when: gpg_res.rc != 0
     args:
       warn: false


   - name: Docker - Install Docker-repo_1
     shell: dpkg --print-architecture
     register: var_1

   - name: Docker - Install Docker-repo_2
     shell: lsb_release -cs
     register: var_2

   - name: Docker - set fact
     set_fact:
       repo_var_1={{ var_1.stdout }}
       repo_var_2={{ var_2.stdout }}


   - name: Docker - Install Docker-repo
     blockinfile:
       create: yes
       path: /etc/apt/sources.list.d/docker.list
       block: |
         deb [arch={{ var_1.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ var_2.stdout }} stable

   - name: Docker - Install Docker-ce
     apt:
      name: docker-ce,docker-ce-cli,containerd.io
      state: present
      update_cache: yes

   - name: Docker - Create Docker Directory
     file:
       path: /etc/docker
       state: directory

   - name: Docker - Create Docker Daemon
     blockinfile:
       create: yes
       path: /etc/docker/daemon.json
       block: |
         {
           "exec-opts": ["native.cgroupdriver=systemd"],
           "log-driver": "json-file",
           "log-opts": {
            "max-size": "100m"
           },
         "storage-driver": "overlay2"
         }

   - name: Docker - Start Docker Service
     systemd:
       name: docker
       daemon-reload: yes
       enabled: yes
