- name: delete vm instances
  hosts: localhost
  gather_facts: false
  vars_files: vm_list.yaml

  tasks:
  - name: delete instances
    gcp_compute_instance:
      project: "{{ gcp_project }}"
      zone: "{{ zone }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ playbook_dir }}/{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: absent
      name: "{{ item.vm_name }}"
    with_items:
      "{{ vm_list }}"


  - name: delete remain boot disk
    gcp_compute_disk:
      project: "{{ gcp_project }}"
      zone: "{{ zone }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ playbook_dir }}/{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      name: "{{ item.boot_disk_name }}"
      state: absent
    register: disk
    with_items:
      "{{ vm_list }}"