- name: Create an instance
  hosts: localhost
  gather_facts: false
  vars_files: vm_list.yaml

  tasks:

  - name: create a disk
    gcp_compute_disk:
      project: "{{ gcp_project }}"
      zone: "{{ zone }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ playbook_dir}}/{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      labels:
        user: wocheon07

      name: "{{ item.boot_disk_name }}"
      state: "{{ item.vm_onoff }}"
      size_gb: "{{ item.boot_disk_size }}"
      source_image: "{{ item.boot_disk_image }}"
        #source_snapshot:
         # selfLink: "{{ disk_snapshot }}"
    register: disk
    with_items:
      "{{ vm_list }}"

  - name: create vm
    gcp_compute_instance:
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ playbook_dir}}/{{ gcp_cred_file }}"
      state: "{{ item.vm_onoff }}"
      deletion_protection: no
      status: "{{ item.vm_status }}"
      name: "{{ item.vm_name }}"
      machine_type: "{{ item.machine_type }}"
      labels:
        user: wocheon07
      disks:
        - auto_delete: true
          boot: true
          source:
            selfLink: "https://www.googleapis.com/compute/v1/projects/{{ gcp_project }}/zones/{{ zone }}/disks/{{ item.boot_disk_name }}"
      network_interfaces:
        - network:
            selfLink: "{{ network }}"
          subnetwork:
            selfLink: "{{ subnetwork }}"
          network_ip: "{{ item.vm_ip }}"
          access_configs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      scopes:
        - https://www.googleapis.com/auth/compute
    register: instance
    with_items:
      "{{ vm_list }}"

