---
 - name: install docker
   hosts: k8s
   become: yes
   gather_facts: no
   tasks:
   
   - name: install dependency & repo
     shell: |
       yum install -y yum-utils device-mapper-persistent-data lvm2 
       yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     register: output_1
   - debug: var=output_1.stdout_lines  

   - name: install docker
     shell: |
       yum install -y docker-ce
       systemctl enable docker --now
     register: output_1
   - debug: var=output_1.stdout_lines  
       
   - name: prepare install k8s
     shell: |
       cat <<EOF > /etc/sysctl.d/k8s.conf
       net.bridge.bridge-nf-calll-ip6tables = 1
       net.bridge.bridge-nf-calll-iptables = 1
       EOF
       sysctl --system
       systemctl disable firewalld --now
       swapoff -a
     register: output_1
   - debug: var=output_1.stdout_lines  

---
 - name: install k8s
   hosts: k8s
   become: yes
   gather_facts: no
   tasks:
   - name: install k8s repo
     shell: |
       cat <<EOF > /etc/yum.repos.d/kubernetes.repo
       [kubernetes]
       name=Kubernetes
       baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
       enabled=1
       gpgcheck=1
       gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
       exclude=kube*
       EOF
     register: output_2
   - debug: var=output_2.stdout_lines  

   - name: install k8s
     shell: |
       yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
       systemctl enable kubelet --now
     register: output_2
   - debug: var=output_2.stdout_lines  

   - name: prepare CNI set
     shell: |
       echo "1"> /proc/sys/net/bridge/bridge-nf-call-iptables
       echo "1" > /proc/sys/net/ipv4/ip_forward
       rm -rf /etc/containerd/config.toml
       systemctl restart containerd     
     register: output_2
   - debug: var=output_2.stdout_lines  
