---
- name: create k8s token
  hosts: master
  become: yes
  gather_facts: no
  tasks:
    - name: kubeadm init 
      shell: |
         kubeadm init --pod-network-cidr=10.244.0.0/16 > "{{ playbook_dir }}"/token
         kubectl completion bash | sudo tee /etc/bash_completion.d/kubectl > /dev/nul
      register: output
    - debug: var=output.stdout_lines    

- name: send token
  hosts: worker
  become: yes
  gather_facts: no
  tasks: 
    - name: send token
      copy:
        src: "{{ playbook_dir }}/token"
        dest: "token"

    - name: join k8s cluster
      shell: tail -2 token | sh
      register: output
    - debug: var=output.stdout_lines    


- name: apply flannel cni plugin
  hosts: master
  become: yes
  gather_facts: no
  tasks:

    - name: apply CNI plugin
      shell: sh cni_setting.sh 
      args:
        chdir: "{{ playbook_dir }}/script" 
      register: output
    - debug: var=output.stdout_lines    


- name: set cni
  hosts: k8s
  become: yes
  gather_facts: no
  tasks:
    - name: set cni
      shell: |
        mkdir -p /run/flannel/
        echo "FLANNEL_NETWORK=10.244.0.0/16" >> /run/flannel/subnet.env
        echo "FLANNEL_SUBNET=10.244.1.0/24 " >> /run/flannel/subnet.env
        echo "FLANNEL_MTU=1450" >> /run/flannel/subnet.env
        echo "FLANNEL_IPMASQ=true" >> /run/flannel/subnet.env

    - name: restart service
      shell: |
        systemctl restart containerd
        systemctl restart kubelet
