---
- name: create k8s token
  hosts: master
  become: yes
  gather_facts: no
  tasks:
    - name: create token
      shell: kubeadm init>token
    
    - name: get tokenfile
      fetch:
        src: "/root/token"
        dest: "token"
        flat: yes

    - name: copy cni_setting.sh
      copy:
        src: "cni_setting.sh"
        dest: "cni_setting.sh"

    - name: apply CNI plugin
      shell: sh cni_setting.sh 

- name: send token
  hosts: worker
  become: yes
  gather_facts: no
  tasks: 
    - name: send token
      copy:
        src: "token"
        dest: "token"
    - name: join k8s cluster
      shell: tail -2 token | sh

- name: set cni
  hosts: k8s
  become: yes
  gather_facts: no
  tasks:
    - name: set cni
      shell: |
        mkdir -p /run/flannel/
        echo "FLANNEL_NETWORK=10.244.0.0/16" > /run/flannel/subnet.env
        echo "FLANNEL_SUBNET=10.244.0.1/24 " > /run/flannel/subnet.env
        echo "FLANNEL_MTU=1450" > /run/flannel/subnet.env
        echo "FLANNEL_IPMASQ=true" > /run/flannel/subnet.env
