- name: delete vm instances
  hosts: localhost
  gather_facts: false
  vars_files: vm_list.yml

  tasks:
  - name: delete instances
    gcp_compute_instance:
      project: "{{ gcp_project }}"
      zone: "{{ zone }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: absent
      name: "{{ item.vm_name }}"
    with_items:
      "{{ vms }}"
