---
- name: test
  become: true
  gather_facts: no
  hosts: master
  tasks:
    - name: check hostname
      shell: echo "test" 
      register: ipval

    - name: print val
      debug:
        msg:
          - "{{ ipval.stdout }}"


    - name: debug result
      shell: |
        echo "{{ ipval.stdout }}" > "{{ playbook_dir }}"/testfile

    - name: cat result
      shell: cat "{{ playbook_dir }}"/testfile       
      register: output
    - debug: var=output.stdout_lines
