- name: Install nginx web server
  action : "{{ ansible_pkg_mgr }} name=nginx state=present update_cache=yes"
- name: default index.html for web server
  get_url: url=https://www.apache.org dest=/usr/share/nginx/html/ mode=0644 validate_certs=no
  notify:
    - Restart nginx web server
