- name: Create an instance
  hosts: localhost
  gather_facts: false
  vars:
      gcp_project: gcp-in-ca
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /etc/ansible/inventory/service-account.json
      zone: "asia-northeast1-a"
      region: "asia-northeast1"

  tasks:
  - name: create vm
    gcp_compute_instance:
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: present
      name: ansible-vm1
      machine_type: e2-micro
      labels:
        사용자: wocheon07
      disks:
        - auto_delete: true
          boot: true
#         source: "{{ disk }}"
          source:
            selfLink: "projects/gcp-in-ca/zones/asia-northeast1-a/disks/ansible-disk-test"
      network_interfaces:
        - network:
            selfLink: "projects/gcp-in-ca/global/networks/test-vpc-1"
          subnetwork:
            selfLink: "projects/gcp-in-ca/regions/asia-northeast1/subnetworks/test-vpc-sub-03"
          access_configs:
            - name: External NAT
              type: ONE_TO_ONE_NAT
      scopes:
        - https://www.googleapis.com/auth/compute
    register: instance
