---
 - name: install K8S
   hosts: master
   become: yes
   gather_facts: no
   tasks:
   - name: K8S - Prepare Install K8S - 1
     blockinfile:
       path: /etc/sysctl.d/k8s.conf
       create: yes
       block: |
         net.bridge.bridge-nf-calll-ip6tables = 1
         net.bridge.bridge-nf-calll-iptables = 1

   - name: K8S - Prepare Install K8S - 2
     shell: |
       sysctl --system
       systemctl disable firewalld --now
       swapoff -a
     register: sh_res
     changed_when: sh_res.rc != 0

   - name: K8S - Add K8S Repository
     blockinfile:
       path: /etc/yum.repos.d/kubernetes.repo
       create: yes
       block: |
         [kubernetes]
         name=Kubernetes
         baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
         enabled=1
         gpgcheck=1
         gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
         exclude=kube*

   - name: K8S - Install K8S
     yum:
       name: kubelet,kubeadm,kubectl
       disable_excludes: kubernetes
       state: present

   - name: K8S - Start Kubelet Service
     systemd:
       name: kubelet
       enabled: yes


   - name: CNI - net/ipv4/ip_forward=1
     sysctl:
       name: net.ipv4.ip_forward
       value: '1'
       sysctl_set: true

   - name: CNI - check directory  proc/sys/net/bridge
     shell: |
       ls -l /proc/sys/net | grep bridge | wc -l
     register: bridge_chck
     changed_when: bridge_chck.rc != 0
     ignore_errors: true

   - name: CNI - net/bridge/bridge-nf-call-iptables=1
     sysctl:
       name: net.bridge.bridge-nf-call-iptables
       value: '1'
       sysctl_set: true
     when: bridge_chck.stdout != "0"

   - name: CNI - delete /etc/containerd/config.toml
     file:
       path: /etc/containerd/config.toml
       state: absent

   - name: CNI - Restart Containerd Service
     systemd:
       name: containerd
       state: restarted
     register: sys_chck
     changed_when: sys_chck.status.Result != "success"
